# 外部接口
api:
  tushare_token:
  jq_username:
  jq_password: 

# 策略相关参数
strategy:
  rsi_n: 6
  window_size: 12

# 定时任务
scheduler:
  # 扫描所有股票
  scan_time: '00 09 * * MON-FRI'
  # 选股池
  select_time: '05 09 * * MON-FRI'
  # 观察池
  watch_times:
    - '28 10 * * MON-FRI'
    - '28 11 * * MON-FRI'
    - '58 13 * * MON-FRI'
    - '58 14 * * MON-FRI'
  # 校准
  adjust_times:
    - '30 10 * * MON-FRI'
    - '30 11 * * MON-FRI'
    - '00 14 * * MON-FRI'
    - '00 15 * * MON-FRI'